# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      # Cache NPM packages, until package-lock.json changes
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - run: npm ci

      # Upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      # Build the app
      - run: npx tsc

      # Publish to npmjs.com
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
